version: '3'
services:
  nginx:
    restart: always
    container_name: nginxSpell
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '3000:80'
    networks:
      - esnet
  backend:
    container_name: backendSpell
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - MONGODB_HOST=cluster0-3huyc.mongodb.net
      - MONGODB_PORT=
      - MONGODB_DATABASE=laudite
      - MONGODB_USER=spellcheckerDev
      - MONGODB_PASSWORD=RMGZl2emEochz2u7
    networks:
      - esnet
  frontend:
    container_name: frontendSpell
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '8080:8080'
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
     driver: local
  esdata3:
     driver: local

networks:
  esnet:

